# Generated by Django 4.1.5 on 2023-01-31 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0006_localplace'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newmechanic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mech_name', models.CharField(max_length=50)),
                ('mech_contact', models.CharField(max_length=20)),
                ('mech_email', models.CharField(max_length=50)),
                ('mech_address', models.CharField(max_length=80)),
                ('mech_certificate', models.FileField(upload_to='userDocs/')),
                ('password', models.CharField(max_length=50)),
                ('localplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.localplace')),
            ],
        ),
    ]
