# Generated by Django 4.1.5 on 2023-02-01 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newmechanic',
        ),
    ]
