# Generated by Django 4.1.5 on 2023-02-01 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_localplace'),
        ('Guest', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newmechanic',
            name='mech_email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Newmfb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mfb_name', models.CharField(max_length=50)),
                ('mfb_contact', models.CharField(max_length=20)),
                ('mfb_email', models.EmailField(max_length=254, null=True, unique=True)),
                ('mfb_address', models.CharField(max_length=80)),
                ('mfb_liscence', models.FileField(upload_to='userDocs/')),
                ('password', models.CharField(max_length=50)),
                ('localplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.localplace')),
            ],
        ),
    ]
