# Generated by Django 4.1.5 on 2023-02-01 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_localplace'),
        ('Guest', '0004_alter_newmechanic_mech_email_newmfb'),
    ]

    operations = [
        migrations.AddField(
            model_name='newmechanic',
            name='doj',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='newmechanic',
            name='mech_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newmfb',
            name='doj',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='newmfb',
            name='mfb_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='newmechanic',
            name='password',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='newmfb',
            name='password',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='Newusr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usr_name', models.CharField(max_length=50)),
                ('usr_contact', models.CharField(max_length=20)),
                ('usr_email', models.EmailField(max_length=254, unique=True)),
                ('usr_address', models.TextField(null=True)),
                ('usr_gender', models.CharField(max_length=20)),
                ('usr_dob', models.DateField()),
                ('password', models.CharField(max_length=50, unique=True)),
                ('doj', models.DateTimeField(auto_now_add=True, null=True)),
                ('localplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.localplace')),
            ],
        ),
    ]
