# Generated by Django 4.1.5 on 2023-02-01 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0005_newmechanic_doj_newmechanic_mech_status_newmfb_doj_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admindb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admn_name', models.CharField(max_length=50)),
                ('admn_email', models.EmailField(max_length=254, null=True, unique=True)),
                ('password', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='newusr',
            name='usr_photo',
            field=models.FileField(null=True, upload_to='userDocs/'),
        ),
    ]
