# Generated by Django 4.1.5 on 2023-02-07 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0006_localplace'),
        ('Guest', '0006_admindb_newusr_usr_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repairschedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.CharField(max_length=120)),
                ('landmark', models.CharField(max_length=50)),
                ('model_name', models.CharField(max_length=50)),
                ('model_year', models.CharField(max_length=50)),
                ('issue_note', models.CharField(max_length=120)),
                ('dt_of_booking', models.DateTimeField(auto_now_add=True)),
                ('booking_status', models.IntegerField(default=0)),
                ('mid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.newmechanic')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.newusr')),
                ('veh_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.brand')),
            ],
        ),
    ]
