# Generated by Django 4.1.5 on 2023-02-08 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_localplace'),
        ('Guest', '0006_admindb_newusr_usr_photo'),
        ('User', '0002_rename_mid_repairschedule_mechid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mfbschedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.CharField(max_length=120)),
                ('landmark', models.CharField(max_length=50)),
                ('fuel_type', models.CharField(max_length=50)),
                ('fuel_amount', models.CharField(default=0, max_length=50)),
                ('dt_of_booking', models.DateTimeField(auto_now_add=True)),
                ('booking_status', models.IntegerField(default=0)),
                ('mfbid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.newmechanic')),
                ('usrid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.newusr')),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.vehicletype')),
            ],
        ),
    ]
