# Generated by Django 4.1.5 on 2023-02-12 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0006_admindb_newusr_usr_photo'),
        ('User', '0005_alter_mfbschedule_mfbid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usrfeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=500)),
                ('dt_of_feedback', models.DateTimeField(auto_now_add=True)),
                ('usrid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.newusr')),
            ],
        ),
        migrations.CreateModel(
            name='Usrcomplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=500)),
                ('dt_of_compreg', models.DateTimeField(auto_now_add=True)),
                ('usrid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.newusr')),
            ],
        ),
    ]
