# Generated by Django 4.1.5 on 2023-02-20 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_usrfeedback_usrcomplaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='usrcomplaint',
            name='feedback_status',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
