# Generated by Django 4.1.5 on 2023-02-20 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_usrcomplaint_feedback_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usrcomplaint',
            name='feedback_status',
        ),
    ]
