# Generated by Django 4.1.5 on 2023-02-20 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_remove_usrcomplaint_feedback_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='usrcomplaint',
            name='complaint_response',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usrcomplaint',
            name='complaint_status',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
