from django.urls import path
from Admin import views
app_name="projectadmin"
urlpatterns = [
    path('state/',views.state,name="state"),
    path('district/',views.district,name="district"),
    path('vehicletype/',views.vehicletype,name="vehicletype"),
    path('brand/',views.brand,name="brand"),
    path('editstate/<int:sid>',views.editstate,name="editstate"),
    path('delstate/<int:sid>',views.delstate,name="delstate"),
    path('deldistrict/<int:did>',views.deldistrict,name="deldistrict"),
    path('editvehicletype/<int:vtid>',views.editvehicletype,name="edit"),
    path('delvehicletype/<int:vtid>',views.delvehicletype,name="delvehicletype"),
    path('delbrand/<int:bid>',views.delbrand,name="delbrand"),
    path('place/',views.place,name="place"),
    path('ajaxplace/',views.Ajaxplace,name="Ajax-place"),
    path('delplace/<int:pid>',views.delplace,name="delplace"),
    path('localplace/',views.localplace,name="localplace"),
    path('ajaxlocalplace/',views.Ajaxlocalplace,name="Ajax-localplace"),
    path('dellocalplace/<int:lpid>',views.dellocalplace,name="dellocalplace"),
    path('adminhome/',views.adminhome,name="adminhome"),
    path('mechverification/',views.mechverification,name="mechverification"),
    path('acceptmech/<int:acceptmechid>',views.acceptmech,name="acceptmech"),
    path('rejectmwech/<int:rejectmechid>',views.rejectmwech,name="rejectmwech"),
    path('aceptedrequests/',views.aceptedrequests,name="aceptedrequests"),
    path('rejectedrequests/',views.rejectedrequests,name="rejectedrequests"),
    path('mfbverification/',views.mfbverification,name="mfbverification"),
    path('acceptmfb/<int:acceptmfbid>',views.acceptmfb,name="acceptmfb"),
    path('rejectmfb/<int:rejectmfbid>',views.rejectmfb,name="rejectmfb"),
    path('aceptedmfbrequests/',views.aceptedmfbrequests,name="aceptedmfbrequests"),
    path('rejectedmfbrequests/',views.rejectedmfbrequests,name="rejectedmfbrequests"),
    path('viewfeedback/',views.viewfeedback,name="viewfeedback"),
    path('complaints/',views.complaints,name="complaints"),
    path('respond/<int:compid>',views.respond,name="respond"),
    path('mechpaymentreport/',views.paymentreportmechanic,name="mechpaymentreport"),
    path('paymentreportmfb/',views.paymentreportmfb,name="paymentreportmfb"),
    path('logout/',views.logout,name="logout"),
]